In [1]:
i = 10
a = []
for i in range(i):
  print("Enter number")
  num = int(input())
  a.append(num)
print(a)

Enter number
10
Enter number
20
Enter number
3
Enter number
4
Enter number
5
Enter number
6
Enter number
7
Enter number
8
Enter number
9
Enter number
0
['10', '20', '3', '4', '5', '6', '7', '8', '9', '0']

In [6]:
j = '21'
if j in a:
    print("True")
else:
    print("False")

False

In [4]:
a

['10', '20', '3', '4', '5', '6', '7', '8', '9', '0']

In [7]:
i = 20
a = []
for i in range(i):
  print("Enter number")
  num = int(input())
  a.append(num)
print(a)

Enter number
1
Enter number
2
Enter number
3
Enter number
4
Enter number
5
Enter number
6
Enter number
7
Enter number
8
Enter number
9
Enter number
10
Enter number
11
Enter number
12
Enter number
12
Enter number
13
Enter number
14
Enter number
15
Enter number
16
Enter number
17
Enter number
18
Enter number
19
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12, 13, 14, 15, 16, 17, 18, 19]

In [8]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12, 13, 14, 15, 16, 17, 18, 19]

In [15]:
count_positive = 0
count_negative = 0
for i in a:
    if i > 0:
        count_positive = count_positive +1
    else:
        count_negative = count_negative + 1

In [16]:
count_positive

18

In [12]:
a[2] = -3
a[6] = -8

In [17]:
count_negative

2

In [18]:
a

[1, 2, -3, 4, 5, 6, -8, 8, 9, 10, 11, 12, 12, 13, 14, 15, 16, 17, 18, 19]

In [19]:
a[-1]

19

In [20]:
a[-2]

18

In [21]:
a[-3]

17

In [22]:
len(a)

20

In [23]:
a[20-1]

19

In [24]:
a[-1]

19

In [25]:
count_odd = 0
count_even = 0
for i in a:
    if i % 2 != 0:
        count_odd += 1
    else:
        count_even += 1

In [27]:
count_odd,count_even

(9, 11)

In [28]:
a

[1, 2, -3, 4, 5, 6, -8, 8, 9, 10, 11, 12, 12, 13, 14, 15, 16, 17, 18, 19]

In [38]:
sum = 0
for i in a:
    sum = sum + i
l = len(a)

In [39]:
sum/l

9.05

In [33]:
a.sort()

In [34]:
a

[-8, -3, 1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 12, 13, 14, 15, 16, 17, 18, 19]

In [35]:
a[0]

-8

In [36]:
a[-1]

19

In [40]:
dup = [1,2,3,3,4,2,1,10]

# [1,2,3,4.10]

In [ ]:
1:2
2:2
3:2
4:1
10:1

d[1] = 1
d[2] = 1
d[3] = 2

d { 1 : 2, 2: 2, 3:2,4:1.10:1}

In [ ]:
for i in keys:
    a.append(keys)

In [41]:
import pandas as pd

In [42]:
URL = "https://www.epa.gov/sites/default/files/2021-03/state_tier1_caps.xlsx"
 
df = pd.read_excel(URL, sheet_name="State_Trends", header=1)
print(df)

      State FIPS State  Tier 1 Code      Tier 1 Description Pollutant  \
0              1    AL            1  FUEL COMB. ELEC. UTIL.        CO
1              1    AL            1  FUEL COMB. ELEC. UTIL.       NH3
2              1    AL            1  FUEL COMB. ELEC. UTIL.       NOX
3              1    AL            1  FUEL COMB. ELEC. UTIL.  PM10-PRI
4              1    AL            1  FUEL COMB. ELEC. UTIL.  PM25-PRI
...          ...   ...          ...                     ...       ...
5314          56    WY           16        PRESCRIBED FIRES       NOX
5315          56    WY           16        PRESCRIBED FIRES  PM10-PRI
5316          56    WY           16        PRESCRIBED FIRES  PM25-PRI
5317          56    WY           16        PRESCRIBED FIRES       SO2
5318          56    WY           16        PRESCRIBED FIRES       VOC

      emissions90  emissions96  emissions97  emissions98  emissions99  ...  \
0         6.86859      8.06884      8.04705      8.12158    11.515260  ...
1             NaN      0.01516      0.01605      0.01597     0.016510  ...
2       187.79386    219.00900    209.98918    198.66722   186.387100  ...
3         8.85994      9.28102      8.83472      8.37946    29.217020  ...
4         3.60246      4.36618      4.23529      4.00666    25.092193  ...
...           ...          ...          ...          ...          ...  ...
5314          NaN          NaN          NaN          NaN          NaN  ...
5315          NaN          NaN          NaN          NaN          NaN  ...
5316          NaN          NaN          NaN          NaN          NaN  ...
5317          NaN          NaN          NaN          NaN          NaN  ...
5318          NaN          NaN          NaN          NaN          NaN  ...

      emissions12  emissions13  emissions14  emissions15  emissions16  \
0        9.642311     9.326977     9.011643     9.125182     9.238721
1        0.488463     0.487606     0.486749     0.457457     0.428165
2       57.768312    53.849475    49.930638    40.769235    31.607833
3        6.469981     5.616641     4.763300     3.950869     3.138437
4        4.407621     3.949151     3.490680     2.964636     2.438592
...           ...          ...          ...          ...          ...
5314     2.700751     1.685790     0.670829     0.723065     0.775301
5315    25.776110    16.050751     6.325392     6.152275     5.979158
5316    21.844143    13.602321     5.360500     5.213792     5.067083
5317     1.698021     1.058455     0.418889     0.426659     0.434428
5318    61.320442    38.175952    15.031462    14.476352    13.921243

      emissions17  emissions18  emissions19  emissions20  emissions21
0        9.323161    10.050146     8.243679     8.243679     8.243679
1        0.398873     0.455760     0.417551     0.417551     0.417551
2       22.422130    26.233104    19.592480    13.752790    11.162100
3        2.303326     2.601011     2.868642     2.868642     2.868642
4        1.898368     1.941267     2.659792     2.659792     2.659792
...           ...          ...          ...          ...          ...
5314     0.827537     0.893848     0.374873     0.374873     0.374873
5315     5.806041     7.118097     2.857886     2.857886     2.857886
5316     4.920375     6.032286     2.421937     2.421937     2.421937
5317     0.442197     0.509242     0.208817     0.208817     0.208817
5318    13.366133    16.632343     6.645249     6.645249     6.645249

[5319 rows x 32 columns]

In [43]:
df_all_co = df[df["Pollutant"]=="CO"][["State", "Tier 1 Description", "emissions21"]]
print(df_all_co)

     State             Tier 1 Description  emissions21
0       AL         FUEL COMB. ELEC. UTIL.     8.243679
7       AL          FUEL COMB. INDUSTRIAL    17.291741
14      AL               FUEL COMB. OTHER    29.201838
21      AL  CHEMICAL & ALLIED PRODUCT MFG     2.626484
28      AL              METALS PROCESSING    12.167189
...    ...                            ...          ...
5284    WY               HIGHWAY VEHICLES    59.719298
5291    WY                    OFF-HIGHWAY    30.612400
5298    WY                  MISCELLANEOUS     3.828401
5305    WY                      WILDFIRES    89.399972
5312    WY               PRESCRIBED FIRES    28.177445

[760 rows x 3 columns]

In [44]:
df_pivot = df_all_co.pivot_table(index="State", columns="Tier 1 Description", values="emissions21")
print(df_pivot)

Tier 1 Description  CHEMICAL & ALLIED PRODUCT MFG  FUEL COMB. ELEC. UTIL.  \
State
AK                                            NaN                4.679098
AL                                       2.626484                8.243679
AR                                       0.307811                5.027354
AZ                                       0.000000                4.483514
CA                                       0.876666                6.819343
CO                                       0.013220                7.410508
CT                                            NaN                0.524795
DC                                            NaN                     NaN
DE                                       0.007891                0.477802
FL                                       0.097017               23.433428
GA                                       0.684786                8.080826
HI                                            NaN                1.480534
IA                                       0.564369               12.197362
ID                                       0.531697                0.240051
IL                                       1.240725               13.672972
IN                                       0.285520               10.263646
KS                                       1.764507               10.661365
KY                                       0.157598               10.088503
LA                                      12.148681               14.124339
MA                                       0.000038                1.126928
MD                                       0.312314                2.119486
ME                                            NaN                2.278409
MI                                       0.169758               13.362612
MN                                       0.106981                6.877005
MO                                       1.531638               15.628293
MS                                       5.683430                9.365678
MT                                       0.239646                2.312470
NC                                       0.587754               12.126342
ND                                       0.034985                5.686924
NE                                       0.085690               12.182681
NH                                            NaN                1.891372
NJ                                       0.080199                2.203424
NM                                            NaN                6.025603
NV                                            NaN                3.312232
NY                                       0.128797                7.255136
OH                                      44.233978                8.349429
OK                                       1.442616               10.631008
OR                                       0.158320                3.709405
PA                                       0.273742               24.852067
RI                                            NaN                0.811315
SC                                       1.218940                7.322689
SD                                            NaN                0.459704
TN                                      14.557758                3.309555
TX                                       7.702839              105.641413
UT                                       0.123703               10.765954
VA                                       0.065439                5.569961
VT                                            NaN                1.343603
WA                                       0.116416                4.831139
WI                                       0.023691                7.422521
WV                                       0.206324                7.836174
WY                                      14.296860               14.617882

Tier 1 Description  FUEL COMB. INDUSTRIAL  FUEL COMB. OTHER  HIGHWAY VEHICLES  \
State
AK                               7.780446        225.802864         57.092934
AL                              17.291741         29.201838        466.105354
AR                              23.058056         46.680001        203.971567
AZ                               1.763194         15.810092        384.568563
CA                              31.690680        149.373372        546.577559
CO                              16.428686         38.713344        289.015039
CT                               2.450608         29.750289        111.544247
DC                               0.012720          0.961035         20.413995
DE                               1.152836          6.360569         39.567587
FL                              23.129794         68.145129       1128.232692
GA                              14.280708         53.868569        648.025292
HI                               0.334582          1.567338         66.576138
IA                              12.285565         29.145228        197.681732
ID                               7.059251         13.012514        111.295539
IL                              30.679828         63.015580        510.984209
IN                              47.888407         59.167689        448.204886
KS                              13.471917         21.164352        188.301167
KY                               9.906762         62.111465        290.090728
LA                              64.427344         11.482425        272.475895
MA                               5.889776         44.074335        201.764269
MD                               3.042098         45.373180        209.521118
ME                              15.231371         57.321036         58.721181
MI                              26.601335         93.024860        530.065940
MN                              16.141919        241.094836        334.639436
MO                               4.572263        113.755732        436.576169
MS                              31.490222         24.616653        226.925898
MT                               6.228669         12.918277        105.545406
NC                              13.016129         72.762770        594.370534
ND                              14.145077          3.987779         56.699183
NE                               7.883224         12.911302        135.516573
NH                               1.472090         33.969574         58.040044
NJ                               1.757294         54.240444        260.906552
NM                              12.925147         27.235088        168.415293
NV                               2.674123         14.647375        139.105368
NY                              12.003073         88.416265        400.541345
OH                              47.924593         96.893341        562.892705
OK                              50.544551         27.794450        285.382087
OR                               9.542326         63.077603        198.053392
PA                              28.708758        112.423239        436.548818
RI                               0.394245          7.298618         28.953445
SC                              24.211264         19.067792        359.471759
SD                               2.808997          7.946983         67.236964
TN                              15.050397         37.196107        455.318962
TX                              81.638084         33.593820       1260.733388
UT                               2.431652          5.988840        163.991879
VA                              17.646621         70.888038        446.667505
VT                               0.451751         38.944224         24.258516
WA                               8.855538         94.161014        352.113014
WI                              22.624203         98.347127        309.981089
WV                               3.424206         76.559679        110.407667
WY                               9.086374          4.758837         59.719298

Tier 1 Description  METALS PROCESSING  MISCELLANEOUS  OFF-HIGHWAY  \
State
AK                           0.050133       1.745362    53.500832
AL                          12.167189      10.657049   191.953551
AR                           6.066433      39.449980   129.115676
AZ                           0.752409       3.229801   207.813693
CA                           0.209140      38.919176   684.594388
CO                           0.786038       4.119938   256.410710
CT                                NaN       0.042294   115.954425
DC                                NaN       0.000294     7.621835
DE                                NaN       1.176028    54.993046
FL                           0.478888     104.483291   984.323902
GA                           0.331833      21.881502   377.970153
HI                                NaN       2.818326    55.297886
IA                           1.924466      21.605200   144.522166
ID                                NaN      26.412383    82.916724
IL                          15.121210      15.788237   462.754659
IN                         177.452115       6.015476   248.134039
KS                           0.450518      50.802767   118.115177
KY                          48.006390       5.642870   134.826763
LA                           0.608223      47.064453   156.081948
MA                           0.000885       0.760621   237.431660
MD                           0.000384       2.679762   222.062553
ME                                NaN       0.032391    90.402100
MI                          21.552851       2.160932   353.941568
MN                           1.337208      18.296012   305.614239
MO                          28.045594      19.839551   242.976324
MS                           2.232720      18.050369    87.402029
MT                           0.000082      16.095612    52.563661
NC                           2.067680      15.978705   381.997845
ND                                NaN      33.498878    74.074781
NE                           0.003541      16.741767    92.984310
NH                                NaN       0.081125    68.430219
NJ                           0.697463       1.501416   308.473166
NM                                NaN       1.076317    66.352453
NV                           0.243328       0.587727   131.935303
NY                          13.112980       0.946060   602.486197
OH                          49.178214       1.664789   415.949121
OK                           1.351137      33.663222   178.482948
OR                           0.836359      17.310480   203.713829
PA                           6.774812       1.328221   420.454755
RI                                NaN       0.007240    29.858772
SC                          32.260816       9.066709   214.348279
SD                           0.014820       3.897571    44.330047
TN                           3.602404       6.361857   231.128570
TX                           9.816256      46.257670   691.656214
UT                           1.218379       1.480525    99.127759
VA                           2.243837       4.256161   314.474413
VT                                NaN       0.033925    33.524583
WA                          30.180620      27.123893   277.544828
WI                           4.687163       3.363907   254.929211
WV                           2.463119       0.109804    55.100967
WY                                NaN       3.828401    30.612400

Tier 1 Description  OTHER INDUSTRIAL PROCESSES  \
State
AK                                    0.492499
AL                                   31.040208
AR                                   11.111067
AZ                                   11.153465
CA                                   26.858656
CO                                    9.976156
CT                                    1.665355
DC                                    0.288114
DE                                    0.420900
FL                                   19.186928
GA                                   20.650256
HI                                    0.561492
IA                                    4.838715
ID                                    7.755837
IL                                    9.887896
IN                                    8.647622
KS                                    4.811562
KY                                    5.354511
LA                                    9.710530
MA                                    3.082738
MD                                    5.422394
ME                                    3.089512
MI                                   10.586854
MN                                    6.085174
MO                                   19.655915
MS                                    5.597183
MT                                    3.321461
NC                                   12.163407
ND                                    4.863326
NE                                    6.545782
NH                                    0.620018
NJ                                    4.440808
NM                                    1.112405
NV                                    2.822302
NY                                    9.738785
OH                                   12.164690
OK                                    4.442472
OR                                    8.156032
PA                                   11.551278
RI                                    0.512679
SC                                   14.293702
SD                                    2.079916
TN                                    8.577556
TX                                   41.678234
UT                                    3.301629
VA                                   13.009885
VT                                    0.305394
WA                                    7.097585
WI                                    7.140186
WV                                    2.294991
WY                                   14.076030

Tier 1 Description  PETROLEUM & RELATED INDUSTRIES  PRESCRIBED FIRES  \
State
AK                                        4.531370        286.474361
AL                                        6.254160        437.438647
AR                                        6.389661        531.262844
AZ                                        0.016421         66.316136
CA                                        2.357080         97.319417
CO                                       38.004429         56.151980
CT                                             NaN          1.124380
DC                                        0.005749               NaN
DE                                        0.919129          4.251235
FL                                        0.942683       1412.506442
GA                                        0.010534        613.763839
HI                                        0.032899          6.622828
IA                                        0.033791         71.375104
ID                                        0.008702        265.092847
IL                                       22.128303        102.010782
IN                                        3.777286         33.819149
KS                                       49.590157        461.799887
KY                                       19.266318         82.949723
LA                                       30.821824        342.674627
MA                                        0.132749          4.005470
MD                                        0.624204         13.819665
ME                                        0.170858          3.938435
MI                                       12.482970         67.182536
MN                                        0.431585        327.868777
MO                                        0.955796        422.089799
MS                                        2.502095        193.449367
MT                                        4.098156        122.193270
NC                                        1.007221        179.255594
ND                                       32.623624         26.194074
NE                                        0.609771         67.550099
NH                                             NaN          0.701549
NJ                                        0.404403         15.392802
NM                                       54.751213         32.632246
NV                                        0.118508          1.704312
NY                                        0.933905          8.313480
OH                                        2.751967         18.884432
OK                                       44.763426        526.350996
OR                                        0.078676        696.720110
PA                                       56.932203         21.803659
RI                                        0.156012          0.093673
SC                                             NaN        283.986487
SD                                        0.185026         35.916759
TN                                        1.633015        126.734040
TX                                      191.356879        790.449347
UT                                       12.332884         57.792369
VA                                        4.970330        110.095027
VT                                             NaN          2.458492
WA                                        0.123340        282.484318
WI                                        0.061928         58.975099
WV                                       30.517494         69.389620
WY                                       26.366124         28.177445

Tier 1 Description  SOLVENT UTILIZATION  STORAGE & TRANSPORT  \
State
AK                                  NaN             0.056500
AL                             0.168992             0.007686
AR                             0.008284             0.004482
AZ                             0.021141             0.011701
CA                             0.432730             0.492900
CO                             0.025924             1.836220
CT                                  NaN                  NaN
DC                                  NaN                  NaN
DE                                  NaN             0.011732
FL                             0.007007             0.103614
GA                             0.023516             0.027574
HI                             0.000541                  NaN
IA                             0.014691             0.052369
ID                                  NaN             0.148006
IL                             0.013515             0.044271
IN                             0.466687             0.021115
KS                             0.009789             0.078006
KY                             0.002794             0.002877
LA                             0.010450             2.483007
MA                             0.026991                  NaN
MD                             0.008429             0.036800
ME                                  NaN             0.001430
MI                                  NaN             0.019716
MN                             0.009444             0.095920
MO                                  NaN             0.058605
MS                             0.047150             0.011560
MT                                  NaN             0.019376
NC                             0.075526             0.086168
ND                                  NaN             0.009500
NE                             0.001510             0.031925
NH                                  NaN                  NaN
NJ                             0.017795             0.025066
NM                             0.000002             0.007120
NV                             0.011099             0.138142
NY                             0.005217             0.007103
OH                             0.083014             0.025362
OK                                  NaN             0.094044
OR                             0.001666             0.007800
PA                             0.044827             0.070707
RI                                  NaN             0.033318
SC                             0.009960             0.084323

In [45]:
df_melt = df_pivot.melt(value_name="emissions 2021", var_name="Tier 1 Description", ignore_index=False)
print(df_melt)

                  Tier 1 Description  emissions 2021
State
AK     CHEMICAL & ALLIED PRODUCT MFG             NaN
AL     CHEMICAL & ALLIED PRODUCT MFG        2.626484
AR     CHEMICAL & ALLIED PRODUCT MFG        0.307811
AZ     CHEMICAL & ALLIED PRODUCT MFG        0.000000
CA     CHEMICAL & ALLIED PRODUCT MFG        0.876666
...                              ...             ...
VT                         WILDFIRES        0.000000
WA                         WILDFIRES      160.284327
WI                         WILDFIRES        0.911783
WV                         WILDFIRES        5.086241
WY                         WILDFIRES       89.399972

[765 rows x 2 columns]

In [ ]:
df_sum = df[df["Pollutant"]=="CO"].groupby("State").sum()
print(df_sum)

In [49]:
df2 = df[df["Pollutant"]=="CO"].groupby("State")

In [50]:
df2.get_group("AZ")

,State FIPS,State,Tier 1 Code,Tier 1 Description,Pollutant,emissions90,emissions96,emissions97,emissions98,emissions99,...,emissions12,emissions13,emissions14,emissions15,emissions16,emissions17,emissions18,emissions19,emissions20,emissions21
206,4,AZ,1,FUEL COMB. ELEC. UTIL.,CO,5.75614,5.35889,5.90223,6.40334,6.309220,...,10.326365,10.678308,11.030250,9.656707,8.283165,6.892862,5.822987,4.483514,4.483514,4.483514
213,4,AZ,2,FUEL COMB. INDUSTRIAL,CO,8.87428,11.99587,12.15166,12.08552,7.963453,...,1.649713,1.752392,1.855071,1.799205,1.743338,1.704231,1.819332,1.763194,1.763194,1.763194
220,4,AZ,3,FUEL COMB. OTHER,CO,53.13644,13.41955,13.43358,13.39981,14.124984,...,20.810753,22.627687,24.444621,21.561627,18.678633,15.795640,15.780095,15.810092,15.810092,15.810092
227,4,AZ,4,CHEMICAL & ALLIED PRODUCT MFG,CO,0.00034,0.00102,0.00108,0.00111,0.001480,...,0.002597,0.002559,0.002520,0.002337,0.002153,0.001970,0.000380,0.000000,0.000000,0.000000
234,4,AZ,5,METALS PROCESSING,CO,0.42942,1.66495,1.74125,1.72200,0.220072,...,0.630213,0.632975,0.635737,0.674148,0.712560,0.750971,0.776635,0.752409,0.752409,0.752409
241,4,AZ,6,PETROLEUM & RELATED INDUSTRIES,CO,3.38203,2.01507,2.15681,2.18672,1.050732,...,0.067767,0.045081,0.022395,0.018945,0.015494,0.012044,0.009776,0.016421,0.016421,0.016421
248,4,AZ,7,OTHER INDUSTRIAL PROCESSES,CO,4.33391,8.83744,9.33055,9.43153,3.602080,...,6.173717,8.145892,10.118068,9.496498,8.874928,8.253307,9.327376,11.153465,11.153465,11.153465
255,4,AZ,8,SOLVENT UTILIZATION,CO,NaN,0.00032,0.00033,0.00034,0.013204,...,0.001703,0.002341,0.002980,0.009033,0.015087,0.021141,0.000000,0.021141,0.021141,0.021141
262,4,AZ,9,STORAGE & TRANSPORT,CO,NaN,NaN,NaN,NaN,NaN,...,0.005576,0.005581,0.005585,0.010341,0.015098,0.019905,0.059424,0.011701,0.011701,0.011701
269,4,AZ,10,WASTE DISPOSAL & RECYCLING,CO,23.76316,79.86063,81.78229,90.66058,97.991420,...,20.206385,27.978619,35.750853,25.978739,16.206626,6.434513,6.431018,6.438484,6.438484,6.438484
276,4,AZ,11,HIGHWAY VEHICLES,CO,1616.75178,1084.92615,1065.99933,1049.76456,1017.645150,...,560.612368,557.832176,555.051985,549.795535,468.667272,487.903594,433.685363,413.347655,398.958109,384.568563
283,4,AZ,12,OFF-HIGHWAY,CO,430.98411,494.14342,475.95263,476.65323,481.707176,...,314.575043,302.905888,291.236733,264.541136,209.687297,206.562344,208.337277,205.858288,206.835990,207.813693
290,4,AZ,14,MISCELLANEOUS,CO,415.63088,174.33091,83.62100,132.43087,377.572760,...,4.185652,2.305045,0.424439,0.912196,1.399954,1.887712,3.685007,3.229801,3.229801,3.229801
297,4,AZ,15,WILDFIRES,CO,NaN,NaN,NaN,NaN,NaN,...,1394.221505,1394.221505,231.914128,231.914128,231.914128,369.187816,171.316164,248.713896,248.713896,248.713896
304,4,AZ,16,PRESCRIBED FIRES,CO,NaN,NaN,NaN,NaN,NaN,...,81.166163,77.978816,74.791469,101.381194,127.970919,154.560643,143.925350,66.316136,66.316136,66.316136

In [51]:
df[df["Pollutant"]=="CO"].groupby("State").sum()

,State FIPS,Tier 1 Code,emissions90,emissions96,emissions97,emissions98,emissions99,emissions00,emissions01,emissions02,...,emissions12,emissions13,emissions14,emissions15,emissions16,emissions17,emissions18,emissions19,emissions20,emissions21
State,,,,,,,,,,,,,,,,,,,,,
AK,28,115,4502.12238,883.50805,2421.50089,414.61444,2113.152998,965.370474,318.280263,8689.554049,...,2429.632757,2418.607827,2300.045425,2357.437521,2398.158622,4890.110917,5216.369575,5218.919502,5211.711803,5204.504105
AL,15,123,3404.01163,2440.95216,2369.26803,2361.43903,3011.541333,2265.144310,2151.200553,2139.640782,...,1865.985316,1909.107889,1929.506064,1776.102028,1549.953552,1339.803048,1574.068371,1350.711872,1324.945132,1299.178392
AR,75,123,1706.69006,1356.08524,1326.53142,1345.25313,1293.732544,1253.756263,1232.331321,1182.506250,...,1343.550287,1283.565013,1156.753717,1188.363699,1164.566421,1250.079084,1168.110471,1055.635824,1043.724418,1031.813011
AZ,60,123,2563.04249,1876.55422,1752.07274,1794.73961,2008.201731,1942.665698,1721.562860,2310.468908,...,2414.635520,2407.114865,1237.286833,1217.751771,1094.186652,1259.988694,1000.976184,977.916197,964.504353,951.092509
CA,90,123,15255.07897,11019.29365,10062.82448,9702.05636,8208.233005,9618.345877,7787.477742,5709.540910,...,3444.999810,3215.550865,5604.151765,5426.292799,5227.325184,5730.651458,5313.281485,2159.945594,2119.893468,2079.841343
CO,120,123,2265.79606,2123.23131,1907.21761,1885.17645,1801.101511,2088.859590,1787.469166,2203.830901,...,1277.243113,1140.192103,919.899068,892.376857,804.625242,948.933533,1665.751540,856.871643,842.337995,827.804347
CT,135,123,1544.01353,1173.17385,1147.60725,1129.55606,1211.390050,1056.026736,1040.091669,929.268392,...,420.925114,410.653308,400.149480,373.715891,315.732768,315.571878,286.782696,281.918948,272.761686,263.604424
DC,143,114,156.64046,113.90013,111.42490,109.21359,105.198638,90.531250,92.091739,80.682042,...,43.465353,45.381696,47.298038,44.254796,33.298821,27.621140,29.008520,33.406560,31.356635,29.306709
DE,150,123,434.93355,330.98650,323.60006,319.08832,314.572234,292.168525,296.025553,254.171663,...,127.109054,130.447822,133.389571,131.589801,131.718203,117.715055,114.158440,114.544620,112.169528,109.794436
FL,180,123,7479.26112,6048.65349,5949.32661,5850.57154,7423.826694,6742.137739,7666.186871,6506.884977,...,4165.952383,4256.982808,4206.079211,4000.738337,3532.211533,3286.488652,3526.297712,3914.458210,3907.647563,3900.836915
GA,195,123,5278.20997,4076.22634,3994.38318,4020.28403,4180.349292,3980.800724,3956.533965,3568.890267,...,2809.198850,2797.317443,2192.241364,2184.413607,1934.579903,1906.631877,2246.711903,2046.709979,2007.374387,1968.038794
HI,225,123,539.19242,369.46352,350.04970,339.71547,354.217189,319.776423,310.105406,265.776330,...,223.690847,254.404623,283.937792,240.986741,196.672864,154.907538,170.186041,170.557625,166.699103,162.840580
IA,285,123,1739.13729,1426.03757,1368.96482,1318.10395,1257.390179,1253.256175,1228.007040,1115.514167,...,769.807247,767.609568,772.011519,700.287275,573.909222,521.311870,625.583293,536.843560,523.073864,509.304168
ID,224,118,1112.07840,3842.91708,929.84520,1227.76612,1382.618079,2841.935135,1190.299926,679.068176,...,1094.727647,1078.814837,987.386057,940.780658,867.839749,1988.711592,977.232728,797.517429,789.415208,781.312987
IL,255,123,5475.55995,4308.18782,4202.00036,4127.35310,3942.200056,3787.908628,3666.151363,2908.402673,...,1636.595676,1713.307359,1784.680903,1689.120328,1559.188966,1525.251281,1379.033887,1325.778964,1298.508627,1271.238291
IN,270,123,3682.27917,3282.70736,3177.29833,3089.81552,3105.449385,3072.268546,3036.401383,2473.168019,...,1581.729798,1546.458343,1511.074474,1397.795316,1265.579333,1204.423169,1172.126895,1124.707289,1099.614244,1074.521199
KS,300,123,1942.64784,2290.69382,1488.31949,1326.11171,1228.884776,1247.185231,1206.575950,1786.913609,...,1463.636743,1215.591240,1012.643663,1214.808144,1370.953095,1703.003018,937.987896,970.651528,957.512414,944.373301
KY,315,123,2278.98304,1870.74912,1847.59360,1850.09129,1856.329686,1778.408014,1728.048424,1472.328551,...,1068.773419,1048.487930,1199.042333,1162.014513,1087.751551,901.619977,753.768871,740.388904,722.257403,704.125902
LA,330,123,2583.42254,2415.07635,2386.10670,2392.81293,1888.998311,1934.524052,1783.438671,1603.236720,...,2181.620877,2030.509467,1942.231890,1855.307041,1735.828122,1365.445628,1290.397453,1056.687316,1040.673714,1024.660112
MA,375,123,2746.95118,2238.06597,2175.07598,2138.46811,2181.654319,1894.487641,1847.276100,1350.648436,...,709.512010,702.224767,696.377733,661.578110,605.721186,608.098174,568.311467,554.375318,536.451387,518.527457
MD,360,123,2710.56742,2001.72028,1942.72516,1898.49337,1873.230615,1828.709179,1836.658208,1526.379275,...,742.978991,733.445929,723.355153,712.124529,611.189793,590.526787,550.948572,544.695840,534.973513,525.251185
ME,345,123,1020.08445,671.80241,660.62084,651.48900,593.899443,671.998419,666.388124,565.930511,...,287.988275,285.953735,284.297556,285.105087,271.790481,282.368636,266.082231,254.291548,250.601302,246.911056
MI,390,123,5855.31752,4723.68490,4556.46043,4428.54156,4079.098537,4122.219512,4000.545833,3624.552898,...,1982.956234,1867.938939,1744.856495,1587.068930,1365.093974,1336.820546,1269.607661,1215.050948,1196.170328,1177.289708
MN,405,123,3228.27213,2493.04189,2436.54409,2434.92790,2495.403846,2498.925920,2342.278709,1713.012948,...,2124.698480,2162.257488,1599.119120,1470.709582,1320.695082,1288.194019,1833.908976,1324.301605,1303.255622,1282.209639
MO,435,123,3316.54710,2767.95511,2609.80599,2536.17393,2520.113498,2487.613208,2352.334216,2235.907125,...,1784.524396,1871.898780,1941.764011,1999.981408,2007.992124,2075.886960,1826.810266,1449.910451,1421.619230,1393.328010
MS,420,123,2060.14634,1463.58477,1408.65649,1416.04024,1373.055687,1485.809204,1386.229183,1069.766284,...,1006.881318,963.605845,934.259671,897.055334,790.928012,747.559392,810.603315,680.037021,667.001377,653.965734
MT,450,123,977.26551,1618.92358,767.17205,1106.82999,599.152293,1085.120823,699.537566,563.747786,...,1315.655501,1310.531345,627.049064,573.614630,500.000598,2646.528561,688.987171,414.807719,404.787215,394.766712
NC,555,123,4601.38738,4026.55197,3985.27042,3976.04553,3839.776425,3777.025178,3783.025129,3093.325841,...,1816.534255,1740.767530,1636.685322,1579.725836,1432.883935,1404.087220,1444.644944,1399.592943,1352.592559,1305.592174
ND,532,118,537.20174,541.55217,579.02207,515.95812,393.562318,375.275447,359.396859,301.993293,...,445.809116,403.106979,357.024043,343.184359,327.280166,332.829117,289.383696,264.994537,260.149159,255.303780
NE,465,123,1128.97431,972.79231,860.42251,798.72661,763.300549,780.866994,706.102861,663.522484,...,501.768549,481.647107,463.576275,460.327160,433.608462,427.678156,406.797251,379.241403,369.011896,358.782390
NH,495,123,745.40699,574.18989,563.14348,555.19799,552.000541,531.500624,521.688513,430.338678,...,238.645795,232.603474,226.735340,219.518120,203.859319,202.585240,188.397819,183.866059,181.047766,178.229472
NJ,510,123,3331.24901,2582.09931,2522.96560,2477.24820,2388.482102,2466.005306,2392.789173,1829.382794,...,911.922592,887.106689,908.050468,865.742970,839.902845,780.792889,697.014585,717.465880,692.647457,667.829035
NM,525,123,1403.41947,1138.17165,1116.53513,1055.37627,1113.708745,2377.885439,1053.734271,752.967187,...,1434.379073,1405.610420,513.487610,514.914857,476.267102,624.365899,726.224469,477.241871,466.656630,456.071389
NV,480,123,793.22425,1021.15301,734.45727,745.79494,1284.558302,943.678787,880.077765,457.357705,...,522.893164,497.000357,491.905508,475.889846,452.485780,530.133526,781.806322,330.162485,324.451055,318.739626
NY,540,123,6775.76967,5389.44484,5313.17459,5269.20879,5106.736829,4978.707713,4890.382353,3764.018889,...,1910.644231,1895.945884,1884.248029,1737.137880,1465.599728,1323.831319,1223.282936,1212.804877,1201.385815,1189.966753
OH,585,123,6460.54644,5627.56944,5419.64892,5198.67819,4424.546179,4347.027471,4229.089246,3441.381808,...,2406.780850,2136.861740,1882.226418,1740.186445,1631.417533,1503.512562,1382.197906,1390.601093,1349.084559,1307.568024
OK,600,123,2212.31252,2275.15402,1874.68361,1874.51149,1621.165216,1598.725469,1517.465025,1747.408307,...,1781.930918,1618.775362,1311.016985,1345.125189,1396.930560,1724.418451,1748.314382,1257.844329,1239.264117,1220.683904
OR,615,123,2727.95011,4180.22101,2053.87852,2382.92745,1754.548764,2030.990465,2229.986404,3641.316742,...,2069.430406,1854.150128,2291.871520,2217.264798,2089.620283,3445.294339,2698.359940,1412.832746,1400.830723,1388.828700
PA,630,123,6454.51859,4766.48539,4654.18895,4536.94373,4139.309802,4050.618668,3999.686611,3228.748959,...,1836.228457,1767.271694,1714.286475,1611.334678,1443.681846,1386.083820,1289.308327,1251.980140,1226.736593,1201.493046
RI,660,123,429.62814,295.64900,294.39007,296.48516,287.122275,289.031036,265.760006,174.786610,...,125.364891,124.689122,124.018908,114.783718,93.892193,88.071770,80.920929,75.943590,74.639522,73.335454
SC,675,123,2592.76269,1911.40813,1895.34175,1900.45156,2107.442698,1821.135081,1826.241676,1679.404043,...,1129.520387,1157.962998,1168.364625,1133.531341,1082.313978,1057.987324,1068.302933,1057.916065,1036.249999,1014.583933
SD,690,123,581.62508,480.61632,437.19239,422.56987,412.970939,690.554386,407.934564,303.892012,...,660.875695,613.644306,375.728687,332.368607,275.834360,414.135345,230.077185,179.506253,174.094708,168.683163
TN,705,123,3337.29493,2651.08093,2596.66253,2585.12123,2450.793613,2475.410687,2443.962525,2182.665211,...,1298.219876,1308.650075,1352.034077,1330.632930,1193.046969,1131.871099,1013.040652,1010.186631,985.585883,960.985134
TX,720,123,10259.21951,8317.86568,8200.65488,8308.87838,7848.551794,7669.459861,7362.184972,6224.173221,...,5685.159683,5619.859570,3715.222511,3849.830021,3760.035366,3782.109066,3638.073727,3551.402720,3482.884404,3414.366089
UT,735,123,1315.79283,1350.52217,1042.50231,1042.11711,1257.046387,1287.414795,1188.920254,1004.818369,...,529.313674,512.002752,497.667725,472.069074,418.372217,682.094316,993.597933,469.923025,462.018283,454.113541
VA,765,123,3996.42742,3114.60280,3022.13800,2985.18370,2804.349892,2769.161315,2656.487819,2316.838629,...,1323.723083,1378.369798,1408.290506,1376.189888,1249.115979,1217.830220,1140.440154,1083.923477,1060.934929,1037.946381
VT,750,123,448.30738,339.30571,332.96743,328.19500,331.722305,316.911153,388.350253,292.720550,...,146.647182,144.965831,143.528824,135.554378,121.753611,116.763166,110.414696,107.613694,106.407657,105.201620
WA,795,123,3604.39515,2852.52146,2662.68284,2960.12498,2304.314713,2232.576371,2283.551865,2001.522216,...,1589.880329,1531.784613,2670.332548,2536.212643,2296.065104,2481.467014,1703.948955,1286.715920,1266.983767,1247.251614
WI,825,123,2849.49820,2679.75457,2586.76355,2517.69391,2449.317989,2302.681879,2242.597449,2132.434723,...,1227.017197,1173.315654,1121.268110,1053.614520,898.307407,901.126682,922.375165,872.231181,838.232783,804.234385
WV,810,123,1270.81719,941.39753,921.41038,898.70729,841.281326,925.587150,870.513814,702.797149,...,472.073576,462.042164,502.800156,501.031725,472.318354,438.477319,424.120829,395.720171,387.565561,379.410950
WY,840,123,467.80484,1598.56712,564.75979,530.93897,449.954391,819.630096,462.478081,401.647507,...,1011.528933,900.682591,292.861236,280.296659,253.694516,298.465277,549.270377,306.461296,301.695879,296.930461

In [63]:
df.groupby(["State", "Pollutant"]).sum()[["emissions21"]].reset_index().pivot(index="State", columns="Pollutant", values="emissions21")[["CO","SO2"]]

Pollutant           CO         SO2
State
AK         5204.504105   32.748621
AL         1299.178392   52.698696
AR         1031.813011   55.288823
AZ          951.092509   15.281760
CA         2079.841343   24.732406
CO          827.804347   13.260101
CT          263.604424    2.425462
DC           29.306709    0.052014
DE          109.794436    1.389199
FL         3900.836915   59.882473
GA         1968.038794   33.024725
HI          162.840580   20.150642
IA          509.304168   65.282897
ID          781.312987    6.585505
IL         1271.238291   79.011126
IN         1074.521199   71.218230
KS          944.373301   16.328289
KY          704.125902   58.015104
LA         1024.660112  110.347085
MA          518.527457    4.766306
MD          525.251185    9.745214
ME          246.911056    4.960069
MI         1177.289708   58.592707
MN         1282.209639   25.418112
MO         1393.328010  120.487980
MS          653.965734   12.034537
MT          394.766712   12.219462
NC         1305.592174   24.877304
ND          255.303780  101.391339
NE          358.782390   44.083668
NH          178.229472    5.635965
NJ          667.829035    2.383347
NM          456.071389   13.751060
NV          318.739626    4.498785
NY         1189.966753   14.576765
OH         1307.568024   91.404494
OK         1220.683904   44.921540
OR         1388.828700    9.833770
PA         1201.493046   74.965259
RI           73.335454    0.861648
SC         1014.583933   22.464962
SD          168.683163    2.969323
TN          960.985134   27.670338
TX         3414.366089  257.526011
UT          454.113541   12.810839
VA         1037.946381   18.252264
VT          105.201620    0.711718
WA         1247.251614   13.178053
WI          804.234385   21.141688
WV          379.410950   49.159621
WY          296.930461   37.056612

In [ ]:
import pandas as pd
 
# Pollutants data from Environmental Protection Agency
URL = "https://www.epa.gov/sites/default/files/2021-03/state_tier1_caps.xlsx"
 
# Read the Excel file and print
df = pd.read_excel(URL, sheet_name="State_Trends", header=1)
print("US air pollutant emission data:")
print(df)
 
# Show info
print("\nInformation about the DataFrame:")
df.info()
 
# print dtyes
coltypes = df.dtypes
print("\nColumn data types of the DataFrame:")
print(coltypes)
 
# Get last 3 columns
cols = ["State", "Pollutant", "emissions19", "emissions20", "emissions21"]
last3years = df[cols]
print("\nDataFrame of last 3 years data:")
print(last3years)
 
# Get a series
data2021 = df["emissions21"]
print("\nSeries of 2021 data:")
print(data2021)
 
# Print unique pollutants
print("\nUnique pollutants:")
print(df["Pollutant"].unique())
 
# print mean emission
print("\nMean on the 2021 series:")
print(df["emissions21"].mean())
 
# Describe
print("\nBasic statistics about each column in the DataFrame:")
print(df.describe().T)
 
# Get CO only
df_CO = df[df["Pollutant"] == "CO"]
print("\nDataFrame of only CO pollutant:")
print(df_CO)
 
# Get CO and Highway only
df_CO_HW = df[(df["Pollutant"] == "CO") & (df["Tier 1 Description"] == "HIGHWAY VEHICLES")]
print("\nDataFrame of only CO pollutant from Highway vehicles:")
print(df_CO_HW)
 
# Get DF of all CO
df_all_co = df[df["Pollutant"]=="CO"][["State", "Tier 1 Description", "emissions21"]]
print("\nDataFrame of only CO pollutant, keep only essential columns:")
print(df_all_co)
 
# Pivot
df_pivot = df_all_co.pivot_table(index="State", columns="Tier 1 Description", values="emissions21")
print("\nPivot table of state vs CO emission source:")
print(df_pivot)
 
# melt
df_melt = df_pivot.melt(value_name="emissions 2021", var_name="Tier 1 Description", ignore_index=False)
print("\nMelting the pivot table:")
print(df_melt)
 
# all three are the same
df_filled = df_pivot.fillna(0)
df_filled = df_pivot.where(df_pivot.notna(), 0)
df_filled = df_pivot.mask(df_pivot.isna(), 0)
print("\nFilled missing value as zero:")
print(df_filled)
 
# aggregation
df_sum = df[df["Pollutant"]=="CO"].groupby("State").sum()
print("\nTotal CO emission by state:")
print(df_sum)
 
# group by
df_2021 = ( df.groupby(["State", "Pollutant"])
              .sum()              # get total emissions of each year
              [["emissions21"]]   # select only year 2021
              .reset_index()
              .pivot(index="State", columns="Pollutant", values="emissions21")
              .filter(["CO","SO2"])
          )
print("\nComparing CO and SO2 emission:")
print(df_2021)
 
# join
df_co = df[df["Pollutant"]=="CO"].groupby("State").sum()[["emissions21"]].rename(columns={"emissions21":"CO"})
df_so2 = df[df["Pollutant"]=="SO2"].groupby("State").sum()[["emissions21"]].rename(columns={"emissions21":"SO2"})
df_joined = df_co.join(df_so2)
print("\nComparing CO and SO2 emission:")
print(df_joined)
 
# merge
df_co = df[df["Pollutant"]=="CO"].groupby("State").sum()[["emissions21"]].rename(columns={"emissions21":"CO"}).reset_index()
df_so2 = df[df["Pollutant"]=="SO2"].groupby("State").sum()[["emissions21"]].rename(columns={"emissions21":"SO2"}).reset_index()
df_merged = df_co.merge(df_so2, on="State", how="outer")
print("\nComparing CO and SO2 emission:")
print(df_merged)
 
def minmaxyear(subdf):
    sum_series = subdf.sum()
    year_indices = [x for x in sum_series if x.startswith("emissions")]
    minyear = sum_series[year_indices].astype(float).idxmin()
    maxyear = sum_series[year_indices].astype(float).idxmax()
    return pd.Series({"min year": minyear[-2:], "max year": maxyear[-2:]})
 
df_years = df[df["Pollutant"]=="CO"].groupby("State").apply(minmaxyear)
print("\nYears of minimum and maximum emissions:")
print(df_years)

# Outliers

In [64]:
import numpy as np
import pandas as pd
outliers=[]
def detect_outlier(data_1):
    
    threshold=3
    mean_1 = np.mean(data_1)
    std_1 =np.std(data_1)
    
    
    for y in data_1:
        z_score= (y - mean_1)/std_1 
        if np.abs(z_score) > threshold:
            outliers.append(y)
    return outliers

outlier_datapoints = detect_outlier(dataset)
print(outlier_datapoints)

In [ ]:
sorted(dataset)
q1, q3= np.percentile(dataset,[25,75])
iqr = q3 - q1
lower_bound = q1 -(1.5 * iqr) 
upper_bound = q3 +(1.5 * iqr)

In [66]:
import plotly.express as px

In [ ]:
#create a histogram

fig = px.histogram(df, x=’fare_amount’)

fig.show()

#create a box plot

fig = px.box(df, y=”fare_amount”)

fig.show()

fig = px.scatter(x=df[‘passenger_count’], y=df[‘fare_amount’])

fig.show()

#IQR
def find_outliers_IQR(df):

   q1=df.quantile(0.25)

   q3=df.quantile(0.75)

   IQR=q3-q1

   outliers = df[((df<(q1-1.5*IQR)) | (df>(q3+1.5*IQR)))]
   outliers_dropped = outliers.dropna().reset_index()

   return outliers_dropped



outliers = find_outliers_IQR(df[“fare_amount”])

print(“number of outliers: “+ str(len(outliers)))

print(“max outlier value: “+ str(outliers.max()))


print(“min outlier value: “+ str(outliers.min()))


outliers = find_outliers_IQR(df[[“passenger_count”,”fare_amount”]])

In [ ]:
#upper lower limit
upper_limit = df[‘fare_amount’].mean() + 3*df[‘fare_amount’].std()

print(upper_limit)

lower_limit = df[‘fare_amount’].mean() – 3*df[‘fare_amount’].std()

print(lower_limit)

df[‘fare_amount’] = np.where(df[‘fare_amount’] > upper_limit,

   upper_limit,

   np.where(

       df[‘fare_amount’] < lower_limit,

       lower_limit,

       df[‘fare_amount’]

   )

)

In [ ]:
#Replce with mean

def impute_outliers_IQR(df):

   q1=df.quantile(0.25)

   q3=df.quantile(0.75)

   IQR=q3-q1

   upper = df[~(df>(q3+1.5*IQR))].max()

   lower = df[~(df<(q1-1.5*IQR))].min()

   df = np.where(df > upper,

       df.mean(),

       np.where(

           df < lower,

           df.mean(),

           df

           )

       )

   return df


df[‘fare_amount’] = impute_outliers_IQR(df[‘fare_amount’])

df.describe()[‘fare_amount’]